enum ActionType {
  INCREMENT = 'INCREMENT',
  DECREMENT = 'DECREMENT',
  BEGIN_DELAYED_INCREMENT = 'BEGIN_DELAYED_INCREMENT',
  COMPLETE_DELAYED_INCREMENT = 'COMPLETE_DELAYED_INCREMENT',
}

export default ActionType;
