export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const BEGIN_DELAYED_INCREMENT = "BEGIN_DELAYED_INCREMENT";
export const COMPLETE_DELAYED_INCREMENT = "COMPLETE_DELAYED_INCREMENT";
